---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: mt2022079/spe-mini-project
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: calculator
        image: mt2022079/spe-mini-project
        state: started
        tty: yes
        interactive: yes