---
- name: Pull docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull mt2022079/spe-mini-project

    - name: running container
      shell: docker run -it -d mt2022079/spe-mini-project